"""Reference bank: "what does X look like" examples, chosen from the BENCH split only.

Run:  uv run python -m pipeline.reference_bank [--processed DIR] [--out config/reference_bank.yaml] [--per-label 3]

Bench cases are evaluation-only and are never served to learners (practice, drill, review and both assessment forms
draw from other splits), so showing their radiologist outlines on the reference page cannot leak an answer.

Selection (deterministic; the output is a starting point for a clinician to review and edit):
- only split == "bench" and qa_flags == []
- focal label: prefer cases whose only finding is this one, then cases with fewer findings, then the largest
  area_frac, then the highest contrast; ties by case_id. Within a case, the largest instance of the label.
- pattern label: any bench case with the label, single-finding cases first, then fewer findings; cardiomegaly prefers
  a known, high cardiothoracic ratio; other patterns the largest area_frac.
- normal: bench normals with a known cardiothoracic ratio < 0.5, lowest mean classifier probability first
  (features txv_prob_*), ties by case_id.
- a case is used for one label only where possible (labels with the fewest candidates choose first).
"""

from __future__ import annotations

import argparse
import os
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import yaml

from shared.contracts import Case, Finding

REPO_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = Path(os.environ.get("BLINDSPOT_DATA_DIR", REPO_ROOT / "data"))
DEFAULT_PROCESSED = DATA_DIR / "processed"
DEFAULT_OUT = REPO_ROOT / "config" / "reference_bank.yaml"
TAXONOMY = REPO_ROOT / "config" / "taxonomy.yaml"
SPLIT = "bench"
PER_LABEL = 3
N_NORMAL = 3
NORMAL_CTR_MAX = 0.5
CARDIOMEGALY_CTR_MIN = 0.5

HEADER = """\
# Reference bank for the "what does it look like" page (GET /api/reference).
# GENERATED by `uv run python -m pipeline.reference_bank`; re-running overwrites this file.
# Every case is from the BENCH split: evaluation-only, never served to learners in practice, drill, review or
# assessment, so showing its outline is not a leak. The API drops any entry that is not a bench case.
# CLINICIAN REVIEW: edit freely. Remove or replace an example that is not a clear, typical appearance of its
# label (finding_id = <case_id>#F<n>; look at a candidate in /dev/case/<case_id>).
"""


def load_cases(path: Path) -> list[Case]:
    with path.open() as fh:
        return [Case.model_validate_json(line) for line in fh if line.strip()]


def taxonomy_labels(path: Path = TAXONOMY) -> list[tuple[str, str]]:
    """[(label id, kind)] in taxonomy order."""
    doc = yaml.safe_load(path.read_text()) or {}
    return [(d["id"], d.get("kind", "focal")) for d in doc.get("labels", [])]


# --------------------------------------------------------------------------- pure selection
def eligible(case: Case) -> bool:
    """Bench only, and no QA flag of any kind."""
    return case.split == SPLIT and not case.qa_flags


def best_instance(case: Case, label: str) -> Finding | None:
    """The clearest instance of `label` on the case: largest area, then highest contrast, then lowest id."""
    fs = [f for f in case.findings if f.label == label]
    if not fs:
        return None
    return min(fs, key=lambda f: (-f.area_frac, -(f.contrast or 0.0), f.finding_id))


def _rank_key(case: Case, f: Finding, label: str, kind: str) -> tuple:
    n = len(case.findings)
    if kind == "pattern" and label == "cardiomegaly":
        ctr = case.cardiothoracic_ratio
        known_high = ctr is not None and ctr >= CARDIOMEGALY_CTR_MIN
        return (not known_high, n != 1, n, -(ctr or 0.0), case.case_id)
    return (n != 1, n, -f.area_frac, -(f.contrast or 0.0), case.case_id)


def candidates(cases: Sequence[Case], label: str, kind: str) -> list[tuple[Case, Finding]]:
    """Eligible (case, finding) pairs for `label`, best first."""
    out = []
    for c in cases:
        if not eligible(c):
            continue
        f = best_instance(c, label)
        if f is not None and f.kind == kind:
            out.append((c, f))
    return sorted(out, key=lambda cf: _rank_key(cf[0], cf[1], label, kind))


def _mean_prob(case: Case) -> float:
    ps = [v for k, v in case.features.items() if k.startswith("txv_prob_")]
    return sum(ps) / len(ps) if ps else 1.0


def normal_candidates(cases: Sequence[Case]) -> list[Case]:
    ok = [
        c
        for c in cases
        if eligible(c)
        and c.is_normal
        and not c.findings
        and c.cardiothoracic_ratio is not None
        and c.cardiothoracic_ratio < NORMAL_CTR_MAX
    ]
    return sorted(ok, key=lambda c: (_mean_prob(c), c.case_id))


def select_bank(
    cases: Sequence[Case], labels: Sequence[tuple[str, str]], per_label: int = PER_LABEL, n_normal: int = N_NORMAL
) -> dict[str, Any]:
    """{"version", "split", "labels": {label: [{case_id, finding_id}]}, "normal": [{case_id}]}.

    Labels with the fewest candidates choose first, so a scarce label is not starved by a common one; a case already
    used for another label is taken only when nothing else is left."""
    cands = {lab: candidates(cases, lab, kind) for lab, kind in labels}
    used: set[str] = set()
    chosen: dict[str, list[dict[str, str]]] = {}
    for lab in sorted(cands, key=lambda k: (len(cands[k]), k)):
        fresh = [cf for cf in cands[lab] if cf[0].case_id not in used]
        reused = [cf for cf in cands[lab] if cf[0].case_id in used]
        picks = (fresh + reused)[:per_label]
        used |= {c.case_id for c, _ in picks}
        chosen[lab] = [{"case_id": c.case_id, "finding_id": f.finding_id} for c, f in picks]
    return {
        "version": 1,
        "split": SPLIT,
        "labels": {lab: chosen[lab] for lab, _ in labels},
        "normal": [{"case_id": c.case_id} for c in normal_candidates(cases)[:n_normal]],
    }


def dump_bank(bank: dict[str, Any]) -> str:
    return HEADER + yaml.safe_dump(bank, sort_keys=False, default_flow_style=False, allow_unicode=True)


# --------------------------------------------------------------------------- CLI
def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Select bench-split reference examples per label")
    ap.add_argument("--processed", type=Path, default=DEFAULT_PROCESSED, help="directory holding cases.jsonl")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--per-label", type=int, default=PER_LABEL)
    a = ap.parse_args(argv)
    cases = load_cases(a.processed / "cases.jsonl")
    labels = taxonomy_labels()
    bank = select_bank(cases, labels, per_label=a.per_label)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text(dump_bank(bank))
    n_bench = sum(eligible(c) for c in cases)
    print(f"{a.out}: {n_bench} eligible bench cases (n={len(cases)} total)")
    for lab, _ in labels:
        ids = ", ".join(e["finding_id"] for e in bank["labels"][lab])
        short = "" if len(bank["labels"][lab]) >= a.per_label else "  <-- fewer than requested"
        print(f"  {lab:20s} {len(bank['labels'][lab])}  {ids}{short}")
    print(f"  {'normal':20s} {len(bank['normal'])}  " + ", ".join(e["case_id"] for e in bank["normal"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
