/* eslint-disable */
/* AUTO-GENERATED by scripts/gen-types.mjs from shared/schemas — do not edit. Run `npm run gen:types`. */

export type Level = "MS1" | "MS2" | "MS3" | "MS4" | "intern" | "resident" | "PA/NP student" | "other";

export type Mode = "practice" | "drill" | "assess_A" | "assess_B" | "review";

export type Modality = "cxr" | "ct" | "mr";

export interface Health {
  ok: boolean;
  offline: boolean;
  cases: number;
  version?: string | null;
  tutor?: {
    mode: "live" | "offline" | "paused_credits" | "paused_budget" | "paused_rate" | "paused_error";
    reason?: string | null;
    /**
     * ISO time when live calls will be retried, if paused
     */
    resume_at?: string | null;
    /**
     * hour, day, total (estimates from token counts)
     */
    spend_usd?: {
      [k: string]: number;
    } | null;
    /**
     * hour, day, total limits
     */
    budget_usd?: {
      [k: string]: number;
    } | null;
  } | null;
  modalities?: Modality[] | null;
  cases_by_modality?: {
    [k: string]: number;
  } | null;
}

export interface SessionCreate {
  display_name: string;
  level: Level;
  participant_code?: string | null;
  mode: Mode;
  /**
   * drill: {label}; practice: {prevalence_abnormal}; any: {projector: bool}; modality: cxr|ct|mr (default cxr); body_region
   */
  settings?: {
    [k: string]: unknown;
  };
}

export interface SessionCreated {
  session_id: string;
  learner_id: string;
  mode: Mode;
}

export interface NextCase {
  attempt_id: string;
  case: {
    case_id: string;
    image_url: string;
    width: number;
    height: number;
    modality?: "cxr" | "ct" | "mr";
    body_region?: string | null;
    /**
     * NO ground truth: voxels only. The label volume is never sent before submit.
     */
    volume?: {
      shape: number[];
      spacing: number[];
      window: {
        wc: number;
        ww: number;
      };
      data_url: string;
      sequence?: string | null;
      presets?:
        | {
            name: string;
            wc: number;
            ww: number;
          }[]
        | null;
    } | null;
    /**
     * the '___ by ___' badge; not ground truth
     */
    provenance?: {
      [k: string]: unknown;
    } | null;
  };
  index: number;
  total?: number | null;
  hints_enabled?: boolean;
  done?: boolean;
}

export interface HintRequest {
  marks: Mark[];
  telemetry: TelemetryEvent[];
}

export interface Mark {
  mark_id: string;
  x: number;
  y: number;
  label:
    | "pneumothorax"
    | "effusion"
    | "consolidation"
    | "atelectasis"
    | "nodule"
    | "mass"
    | "calcification"
    | "fracture"
    | "pleural_thickening"
    | "pancreatic_tumour"
    | "liver_tumour"
    | "brain_tumour"
    | "lung_tumour"
    | "colon_tumour"
    | "not_sure";
  confidence: 1 | 2 | 3 | 4 | 5;
  plane?: "axial" | "coronal" | "sagittal" | null;
  slice?: number | null;
  /**
   * [x, y, z] in volume index space (floats). Required for volumetric cases; x,y then hold the in-plane view coords for display.
   *
   * @minItems 3
   * @maxItems 3
   */
  voxel?: [number, number, number] | null;
  /**
   * free-drawn outline in image px (x,y is its centroid); graded by overlap with the finding
   */
  polygon?: [number, number][] | null;
  tool?: "point" | "draw" | null;
}

export interface TelemetryEvent {
  t: number;
  kind: "move" | "down" | "up" | "wheel" | "enter" | "leave" | "loupe" | "wl" | "pan" | "slice" | "plane" | "window";
  x?: number;
  y?: number;
  zoom: number;
  /**
   * @minItems 4
   * @maxItems 4
   */
  vp: [number, number, number, number];
  loupe: boolean;
  plane?: "axial" | "coronal" | "sagittal" | null;
  /**
   * slice index in that plane
   */
  slice?: number | null;
}

export interface HintResponse {
  level: number;
  text: string;
  remaining: number;
}

export interface AskRequest {
  question: string;
}

export interface AskResponse {
  answer: string;
  remaining: number;
  source?: "live" | "template";
}

export interface AssessmentRecorded {
  recorded: true;
  index?: number;
  total?: number;
}

export interface AssessmentSummary {
  session_id: string;
  mode: Mode;
  n_cases: number;
  sensitivity: number | null;
  specificity: number | null;
  localization_fraction: number | null;
  false_positives_per_image: number;
  miss_type_mix: {
    [k: string]: number;
  };
  score_mean: number;
  cases?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export interface ReviewRating {
  reviewer: string;
  role: string;
  item_type: "debrief" | "card";
  item_id: string;
  accuracy: number;
  teaching: number;
  safety_flag: boolean;
  comment?: string | null;
  card_edits?: {
    [k: string]: unknown;
  } | null;
}

export interface SusSubmit {
  learner_id: string;
  /**
   * @minItems 10
   * @maxItems 10
   */
  answers: [number, number, number, number, number, number, number, number, number, number];
}

export interface SusResult {
  score: number;
}

export interface SignSchematic {
  id: string;
  name: string;
  description: string;
  labels: string[];
  modality?: string | null;
  /**
   * inline SVG markup, viewBox 0 0 200 200, cyan/amber/graticule only
   */
  svg: string;
  radiopaedia_url?: string | null;
  review_status?: string;
}

export type Confidence = 1 | 2 | 3 | 4 | 5;

export interface AttemptSubmit {
  marks: Mark[];
  patterns: PatternSelection[];
  declared_normal: boolean;
  normal_confidence?: Confidence | null;
  /**
   * @maxItems 20000
   */
  telemetry: TelemetryEvent[];
  hints_used: number;
  client_timing: {
    shown_at: string;
    submitted_at: string;
  };
  measurements?: Measurement[];
}

export interface PatternSelection {
  label: "cardiomegaly" | "emphysema" | "fibrosis" | "diffuse_nodule";
  confidence: Confidence;
}

export interface Measurement {
  mark_id: string;
  long_mm: number;
  plane: "axial" | "coronal" | "sagittal";
  slice: number;
  p0?: number[] | null;
  p1?: number[] | null;
}

export interface Case {
  case_id: string;
  source: "chestx-det" | "vindr-cxr" | "nih-bbox" | "synthetic" | "msd";
  source_split: string;
  split: "practice" | "assess_A" | "assess_B" | "bench" | "holdout";
  image_path: string;
  width: number;
  height: number;
  pixel_spacing_mm?: number | null;
  is_normal: boolean;
  findings: Finding[];
  anatomy_path?: string | null;
  zones_path?: string | null;
  zones_approximate?: boolean;
  cardiothoracic_ratio?: number | null;
  difficulty_prior?: number;
  features?: {
    [k: string]: number;
  };
  license_tag: string;
  attribution: string;
  qa_flags?: string[];
  modality?: "cxr" | "ct" | "mr";
  body_region?: "chest" | "abdomen" | "brain" | null;
  /**
   * Volumetric cases only. data_path: gzipped int16 little-endian voxels, z,y,x contiguous (index 0 = most superior); mask_path: gzipped uint8 same shape; labels map voxel value → label id or anatomy name. Units: voxel index space; spacing in mm.
   */
  volume?: {
    /**
     * [nz, ny, nx]
     *
     * @minItems 3
     * @maxItems 3
     */
    shape: [number, number, number];
    /**
     * [sz, sy, sx] mm
     *
     * @minItems 3
     * @maxItems 3
     */
    spacing: [number, number, number];
    window: {
      wc: number;
      ww: number;
    };
    data_path: string;
    mask_path: string;
    /**
     * voxel value (as string) → finding label id or anatomy id
     */
    labels: {
      [k: string]: string;
    };
    /**
     * MR sequence name, e.g. T1c, FLAIR
     */
    sequence?: string | null;
    original_shape?: number[] | null;
    /**
     * [z0,y0,x0] of this slab in the original volume
     */
    crop_origin?: number[] | null;
  } | null;
  /**
   * The '___ by ___' badge: who made the reference labels.
   */
  provenance?: {
    dataset: string;
    segmented_by: string;
    readers?: number | null;
    institution?: string | null;
    license?: string | null;
    citation?: string | null;
    url?: string | null;
    grade?: "radiologist" | "clinician" | "model" | "unknown";
  } | null;
}

export interface Finding {
  finding_id: string;
  label:
    | "pneumothorax"
    | "effusion"
    | "consolidation"
    | "atelectasis"
    | "nodule"
    | "mass"
    | "calcification"
    | "fracture"
    | "pleural_thickening"
    | "cardiomegaly"
    | "emphysema"
    | "fibrosis"
    | "diffuse_nodule"
    | "pancreatic_tumour"
    | "liver_tumour"
    | "brain_tumour"
    | "lung_tumour"
    | "colon_tumour";
  source_label: string;
  kind: "focal" | "pattern";
  geometry: {
    kind: "polygon" | "bbox";
    /**
     * x0, y0, x1, y1 in image px
     *
     * @minItems 4
     * @maxItems 4
     */
    bbox: [number, number, number, number];
    polygon?: [number, number][] | null;
    /**
     * 0/255 PNG, same size as the image
     */
    mask_path?: string | null;
  };
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid: [number, number];
  area_frac: number;
  side?: "right" | "left" | "bilateral" | "midline" | null;
  zones?: string[];
  primary_zone?: string | null;
  relative_location?: string | null;
  contrast?: number | null;
  model_prob?: number | null;
  edge_dist?: number | null;
  /**
   * per-finding b0 (M2)
   */
  difficulty?: number | null;
  readers?: number | null;
  agreement?: number | null;
  /**
   * voxel value(s) of this finding in the mask volume; see label_values
   */
  label_value?: number | null;
  label_values?: number[] | null;
  /**
   * [x, y, z] voxel index
   *
   * @minItems 3
   * @maxItems 3
   */
  centroid3?: [number, number, number] | null;
  /**
   * [z0, z1] inclusive axial slices containing the finding
   *
   * @minItems 2
   * @maxItems 2
   */
  slice_range?: [number, number] | null;
  /**
   * longest in-plane diameter on any axial slice (regionprops feret), from the reference mask
   */
  measure?: {
    long_mm: number;
    slice: number;
    plane?: "axial";
  } | null;
  /**
   * sub-structures (e.g. brain tumour: oedema, core, enhancing)
   */
  components?:
    | {
        name: string;
        label_value: number;
      }[]
    | null;
  volume_mm3?: number | null;
}

export interface DebriefFacts {
  schema: "debrief_facts.v1";
  case: {
    case_id: string;
    is_normal: boolean;
    projection: string;
    pixel_spacing_mm?: number | null;
    findings: {
      id: string;
      label: string;
      display: string;
      kind: "focal" | "pattern";
      side?: string | null;
      primary_zone?: string | null;
      zones?: string[];
      relative_location?: string | null;
      size?: string | null;
      difficulty?: "easy" | "moderate" | "hard" | null;
      zones_approximate?: boolean;
      ctr?: number | null;
      slice_range?: number[] | null;
      /**
       * reference longest diameter; only present when measurable
       */
      size_mm?: number | null;
      components?: string[] | null;
      /**
       * names of signs drawn on the reveal for this finding; the debrief may tell the reader to look at them
       */
      signs_drawn?: string[] | null;
    }[];
    modality?: "cxr" | "ct" | "mr";
    body_region?: string | null;
    /**
     * human sentence: 'Reference segmented by an abdominal radiologist (MSD Task07, MSKCC)'
     */
    provenance?: string | null;
  };
  learner: {
    level: string;
    declared_normal: boolean;
    normal_confidence?: number | null;
    hints_used: number;
    time_to_submit_s: number;
    marks: {
      id: string;
      label: string;
      confidence: number;
      zone: string | null;
      plane?: string | null;
      slice?: number | null;
      tool?: string | null;
    }[];
    pattern_selections: {
      label: string;
      confidence: number;
    }[];
    measurements?: {
      mark_id: string;
      long_mm: number;
      plane: string;
    }[];
  };
  outcomes: {
    target: string;
    result:
      | "found"
      | "mislabeled"
      | "missed_search"
      | "missed_recognition"
      | "missed_decision"
      | "pattern_found"
      | "pattern_missed"
      | "pattern_false"
      | "true_positive"
      | "duplicate"
      | "false_positive"
      | "true_negative"
      | "unmatched";
    dwell_ms?: number | null;
    zone?: string | null;
    learner_label?: string | null;
    matched?: string | null;
    size_verdict?: {
      [k: string]: unknown;
    } | null;
    slices_viewed?: boolean | null;
  }[];
  spatial_relations: {
    from: string;
    to: string;
    text: string;
  }[];
  search: {
    lung_coverage_pct: number;
    unvisited_review_areas: string[];
    first_visits: string[];
    zoom_used?: boolean;
    loupe_used?: boolean;
    slices_viewed_pct?: number | null;
    finding_slices_viewed?: {
      [k: string]: boolean;
    } | null;
  };
  /**
   * Per-label {attempts, localized} plus recent_miss_types counts.
   */
  history: {
    recent_miss_types?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  teaching_cards: string[];
}

export interface DebriefOutput {
  headline: string;
  verdict: "all_found" | "partly_found" | "missed" | "overcall" | "correct_normal" | "missed_normal_call";
  findings: {
    finding_id: string;
    result:
      | "found"
      | "mislabeled"
      | "missed_search"
      | "missed_recognition"
      | "missed_decision"
      | "pattern_found"
      | "pattern_missed";
    where_to_look: string;
    what_it_looks_like: string[];
    why: string;
  }[];
  overcalls: {
    mark_id: string;
    /**
     * For 'unmatched' marks on CT/MR say the reference does not label that spot; never call it wrong.
     */
    explanation: string;
    possible_mimics: string[];
  }[];
  search_coaching: string;
  calibration_note: string;
  next_step: string;
  fact_ids: string[];
}

export interface DebriefResponse {
  status: "pending" | "ready" | "failed" | "disabled";
  debrief?: DebriefOutput | null;
  source?: "live" | "cache" | "template" | null;
  provenance?: "ai_draft" | "student_reviewed" | "radiologist_reviewed" | null;
  validator?: {
    [k: string]: unknown;
  } | null;
  latency_ms?: number | null;
  error?: string | null;
}

export type OutcomeResult =
  | "found"
  | "mislabeled"
  | "missed_search"
  | "missed_recognition"
  | "missed_decision"
  | "pattern_found"
  | "pattern_missed"
  | "pattern_false"
  | "true_positive"
  | "duplicate"
  | "false_positive"
  | "true_negative"
  | "unmatched";

export interface SubmitResult {
  score: number;
  success: boolean;
  outcomes: Outcome[];
  reveal: {
    findings: RevealFinding[];
    marks: RevealMark[];
    arrows: Arrow[];
    search: SearchSummary;
    ctr?: number | null;
    is_normal?: boolean;
    zones_approximate?: boolean;
    /**
     * gzipped uint8 label volume, served only after submit
     */
    maskvol_url?: string | null;
    modality?: "cxr" | "ct" | "mr";
    provenance?: {
      [k: string]: unknown;
    } | null;
  };
  facts_card: {
    headline: string;
    lines: string[];
  };
  debrief_status: "pending" | "disabled";
}

export interface Outcome {
  /**
   * finding short id (F1), mark id (M1), or 'case' for true_negative
   */
  target: string;
  result: OutcomeResult;
  dwell_ms?: number | null;
  zone?: string | null;
  /**
   * for marks: the matched finding short id; for findings: the matched mark id
   */
  matched?: string | null;
  learner_label?: string | null;
  size_verdict?: {
    [k: string]: unknown;
  } | null;
  slices_viewed?: boolean | null;
}

export interface RevealFinding {
  /**
   * short id F<n>
   */
  finding_id: string;
  label: string;
  display: string;
  kind: "focal" | "pattern";
  polygon?: [number, number][] | null;
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: [number, number, number, number];
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid?: [number, number] | null;
  side?: string | null;
  zones: string[];
  primary_zone?: string | null;
  relative_location?: string | null;
  result?: OutcomeResult;
  dwell_ms?: number | null;
  slice_range?: number[] | null;
  centroid3?: number[] | null;
  label_values?: number[] | null;
  components?:
    | {
        name: string;
        label_value: number;
      }[]
    | null;
  measure?: {
    long_mm: number;
    slice: number;
    plane?: "axial";
  } | null;
  size_verdict?: {
    your_mm: number;
    reference_mm: number;
    diff_mm: number;
    diff_pct: number;
    ok: boolean;
    plane?: string | null;
  } | null;
  signs?: Sign[] | null;
}

export interface Sign {
  id: string;
  /**
   * e.g. 'Visceral pleural line'
   */
  name: string;
  /**
   * what to look for, one sentence, from the teaching card
   */
  text: string;
  geometry: {
    kind: "polyline" | "polygon" | "circle" | "arrow" | "segment" | "band";
    points: [number, number][];
    radius?: number | null;
    plane?: string | null;
    slice?: number | null;
  };
  /**
   * id of a generic sign schematic (content/signs) when the sign cannot be drawn from the mask
   */
  schematic?: string | null;
}

export interface RevealMark {
  mark_id: string;
  result: "true_positive" | "duplicate" | "false_positive" | "unmatched";
  matched_finding?: string | null;
  zone?: string | null;
  voxel?: number[] | null;
  plane?: string | null;
  slice?: number | null;
  polygon?: [number, number][] | null;
  outline_verdict?: "on_target" | "partly" | "too_broad" | "off" | null;
}

export interface Arrow {
  /**
   * mark id, or null = image centre
   */
  from_mark: string | null;
  to_finding: string;
  text: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  from_xy?: [number, number] | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  to_xy?: [number, number] | null;
  /**
   * short on-film label (≤ 6 words), e.g. 'higher, other lung'
   */
  label?: string | null;
}

export interface SearchSummary {
  lung_coverage_pct: number;
  unvisited_review_areas: string[];
  visited_review_areas?: string[];
  first_visits?: string[];
  time_to_first_mark_s?: number | null;
  total_time_s?: number | null;
  zoom_used?: boolean;
  loupe_used?: boolean;
  heatmap_png_b64?: string | null;
  slice_dwell?:
    | {
        plane: string;
        slice: number;
        ms: number;
        has_finding: boolean;
        finding_ids?: string[] | null;
      }[]
    | null;
  slices_viewed_pct?: number | null;
  /**
   * finding short id → whether any slice holding it was on screen ≥ the threshold
   */
  finding_slices_viewed?: {
    [k: string]: boolean;
  } | null;
}

export interface TeachingCard {
  label: string;
  display_name: string;
  kind: "focal" | "pattern";
  one_liner: string;
  /**
   * @minItems 1
   */
  key_signs: [string, ...string[]];
  where_it_hides: string[];
  mimics: string[];
  commonly_confused_with: string[];
  search_tip: string;
  radiopaedia_url: string | null;
  review: {
    status: "ai_draft" | "student_reviewed" | "radiologist_reviewed";
    reviewer: string | null;
    date: string | null;
    notes: string | null;
  };
  modality?: "cxr" | "ct" | "mr" | null;
}
