/* eslint-disable */
/* AUTO-GENERATED by scripts/gen-types.mjs from shared/schemas — do not edit. Run `npm run gen:types`. */

export type Level = "MS1" | "MS2" | "MS3" | "MS4" | "intern" | "resident" | "PA/NP student" | "other";

export type Mode = "practice" | "drill" | "assess_A" | "assess_B" | "review";

export interface Health {
  ok: boolean;
  offline: boolean;
  cases: number;
  version?: string | null;
}

export interface SessionCreate {
  display_name: string;
  level: Level;
  participant_code?: string | null;
  mode: Mode;
  /**
   * drill: {label}; practice: {prevalence_abnormal}; any: {projector: bool}
   */
  settings?: {
    [k: string]: unknown;
  };
}

export interface SessionCreated {
  session_id: string;
  learner_id: string;
  mode: Mode;
}

export interface NextCase {
  attempt_id: string;
  case: {
    case_id: string;
    image_url: string;
    width: number;
    height: number;
  };
  index: number;
  total?: number | null;
  hints_enabled?: boolean;
  done?: boolean;
}

export interface HintRequest {
  marks: Mark[];
  telemetry: TelemetryEvent[];
}

export interface Mark {
  mark_id: string;
  x: number;
  y: number;
  label:
    | "pneumothorax"
    | "effusion"
    | "consolidation"
    | "atelectasis"
    | "nodule"
    | "mass"
    | "calcification"
    | "fracture"
    | "pleural_thickening"
    | "not_sure";
  confidence: 1 | 2 | 3 | 4 | 5;
}

export interface TelemetryEvent {
  t: number;
  kind: "move" | "down" | "up" | "wheel" | "enter" | "leave" | "loupe" | "wl" | "pan";
  x?: number;
  y?: number;
  zoom: number;
  /**
   * @minItems 4
   * @maxItems 4
   */
  vp: [number, number, number, number];
  loupe: boolean;
}

export interface HintResponse {
  level: number;
  text: string;
  remaining: number;
}

export interface AskRequest {
  question: string;
}

export interface AskResponse {
  answer: string;
  remaining: number;
  source?: "live" | "template";
}

export interface AssessmentRecorded {
  recorded: true;
  index?: number;
  total?: number;
}

export interface AssessmentSummary {
  session_id: string;
  mode: Mode;
  n_cases: number;
  sensitivity: number | null;
  specificity: number | null;
  localization_fraction: number | null;
  false_positives_per_image: number;
  miss_type_mix: {
    [k: string]: number;
  };
  score_mean: number;
  cases?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}

export interface ReviewRating {
  reviewer: string;
  role: string;
  item_type: "debrief" | "card";
  item_id: string;
  accuracy: number;
  teaching: number;
  safety_flag: boolean;
  comment?: string | null;
  card_edits?: {
    [k: string]: unknown;
  } | null;
}

export interface SusSubmit {
  learner_id: string;
  /**
   * @minItems 10
   * @maxItems 10
   */
  answers: [number, number, number, number, number, number, number, number, number, number];
}

export interface SusResult {
  score: number;
}

export type Confidence = 1 | 2 | 3 | 4 | 5;

export interface AttemptSubmit {
  marks: Mark[];
  patterns: PatternSelection[];
  declared_normal: boolean;
  normal_confidence?: Confidence | null;
  /**
   * @maxItems 20000
   */
  telemetry: TelemetryEvent[];
  hints_used: number;
  client_timing: {
    shown_at: string;
    submitted_at: string;
  };
}

export interface PatternSelection {
  label: "cardiomegaly" | "emphysema" | "fibrosis" | "diffuse_nodule";
  confidence: Confidence;
}

export interface Case {
  case_id: string;
  source: "chestx-det" | "vindr-cxr" | "nih-bbox" | "synthetic";
  source_split: string;
  split: "practice" | "assess_A" | "assess_B" | "bench" | "holdout";
  image_path: string;
  width: number;
  height: number;
  pixel_spacing_mm?: number | null;
  is_normal: boolean;
  findings: Finding[];
  anatomy_path?: string | null;
  zones_path?: string | null;
  zones_approximate?: boolean;
  cardiothoracic_ratio?: number | null;
  difficulty_prior?: number;
  features?: {
    [k: string]: number;
  };
  license_tag: string;
  attribution: string;
  qa_flags?: string[];
}

export interface Finding {
  finding_id: string;
  label:
    | "pneumothorax"
    | "effusion"
    | "consolidation"
    | "atelectasis"
    | "nodule"
    | "mass"
    | "calcification"
    | "fracture"
    | "pleural_thickening"
    | "cardiomegaly"
    | "emphysema"
    | "fibrosis"
    | "diffuse_nodule";
  source_label: string;
  kind: "focal" | "pattern";
  geometry: {
    kind: "polygon" | "bbox";
    /**
     * x0, y0, x1, y1 in image px
     *
     * @minItems 4
     * @maxItems 4
     */
    bbox: [number, number, number, number];
    polygon?: [number, number][] | null;
    /**
     * 0/255 PNG, same size as the image
     */
    mask_path?: string | null;
  };
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid: [number, number];
  area_frac: number;
  side?: "right" | "left" | "bilateral" | "midline" | null;
  zones?: string[];
  primary_zone?: string | null;
  relative_location?: string | null;
  contrast?: number | null;
  model_prob?: number | null;
  edge_dist?: number | null;
  /**
   * per-finding b0 (M2)
   */
  difficulty?: number | null;
  readers?: number | null;
  agreement?: number | null;
}

export interface DebriefFacts {
  schema: "debrief_facts.v1";
  case: {
    case_id: string;
    is_normal: boolean;
    projection: string;
    pixel_spacing_mm?: number | null;
    findings: {
      id: string;
      label: string;
      display: string;
      kind: "focal" | "pattern";
      side?: string | null;
      primary_zone?: string | null;
      zones?: string[];
      relative_location?: string | null;
      size?: string | null;
      difficulty?: "easy" | "moderate" | "hard" | null;
      zones_approximate?: boolean;
      ctr?: number | null;
    }[];
  };
  learner: {
    level: string;
    declared_normal: boolean;
    normal_confidence?: number | null;
    hints_used: number;
    time_to_submit_s: number;
    marks: {
      id: string;
      label: string;
      confidence: number;
      zone: string | null;
    }[];
    pattern_selections: {
      label: string;
      confidence: number;
    }[];
  };
  outcomes: {
    target: string;
    result:
      | "found"
      | "mislabeled"
      | "missed_search"
      | "missed_recognition"
      | "missed_decision"
      | "pattern_found"
      | "pattern_missed"
      | "pattern_false"
      | "true_positive"
      | "duplicate"
      | "false_positive"
      | "true_negative";
    dwell_ms?: number | null;
    zone?: string | null;
    learner_label?: string | null;
    matched?: string | null;
  }[];
  spatial_relations: {
    from: string;
    to: string;
    text: string;
  }[];
  search: {
    lung_coverage_pct: number;
    unvisited_review_areas: string[];
    first_visits: string[];
    zoom_used?: boolean;
    loupe_used?: boolean;
  };
  /**
   * Per-label {attempts, localized} plus recent_miss_types counts.
   */
  history: {
    recent_miss_types?: {
      [k: string]: number;
    };
    [k: string]: unknown;
  };
  teaching_cards: string[];
}

export interface DebriefOutput {
  headline: string;
  verdict: "all_found" | "partly_found" | "missed" | "overcall" | "correct_normal" | "missed_normal_call";
  findings: {
    finding_id: string;
    result:
      | "found"
      | "mislabeled"
      | "missed_search"
      | "missed_recognition"
      | "missed_decision"
      | "pattern_found"
      | "pattern_missed";
    where_to_look: string;
    what_it_looks_like: string[];
    why: string;
  }[];
  overcalls: {
    mark_id: string;
    explanation: string;
    possible_mimics: string[];
  }[];
  search_coaching: string;
  calibration_note: string;
  next_step: string;
  fact_ids: string[];
}

export interface DebriefResponse {
  status: "pending" | "ready" | "failed" | "disabled";
  debrief?: DebriefOutput | null;
  source?: "live" | "cache" | "template" | null;
  provenance?: "ai_draft" | "student_reviewed" | "radiologist_reviewed" | null;
  validator?: {
    [k: string]: unknown;
  } | null;
  latency_ms?: number | null;
  error?: string | null;
}

export type OutcomeResult =
  | "found"
  | "mislabeled"
  | "missed_search"
  | "missed_recognition"
  | "missed_decision"
  | "pattern_found"
  | "pattern_missed"
  | "pattern_false"
  | "true_positive"
  | "duplicate"
  | "false_positive"
  | "true_negative";

export interface SubmitResult {
  score: number;
  success: boolean;
  outcomes: Outcome[];
  reveal: {
    findings: RevealFinding[];
    marks: RevealMark[];
    arrows: Arrow[];
    search: SearchSummary;
    ctr?: number | null;
    is_normal?: boolean;
    zones_approximate?: boolean;
  };
  facts_card: {
    headline: string;
    lines: string[];
  };
  debrief_status: "pending" | "disabled";
}

export interface Outcome {
  /**
   * finding short id (F1), mark id (M1), or 'case' for true_negative
   */
  target: string;
  result: OutcomeResult;
  dwell_ms?: number | null;
  zone?: string | null;
  /**
   * for marks: the matched finding short id; for findings: the matched mark id
   */
  matched?: string | null;
  learner_label?: string | null;
}

export interface RevealFinding {
  /**
   * short id F<n>
   */
  finding_id: string;
  label: string;
  display: string;
  kind: "focal" | "pattern";
  polygon?: [number, number][] | null;
  /**
   * @minItems 4
   * @maxItems 4
   */
  bbox: [number, number, number, number];
  /**
   * @minItems 2
   * @maxItems 2
   */
  centroid?: [number, number] | null;
  side?: string | null;
  zones: string[];
  primary_zone?: string | null;
  relative_location?: string | null;
  result?: OutcomeResult;
  dwell_ms?: number | null;
}

export interface RevealMark {
  mark_id: string;
  result: "true_positive" | "duplicate" | "false_positive";
  matched_finding?: string | null;
  zone?: string | null;
}

export interface Arrow {
  /**
   * mark id, or null = image centre
   */
  from_mark: string | null;
  to_finding: string;
  text: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  from_xy?: [number, number] | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  to_xy?: [number, number] | null;
}

export interface SearchSummary {
  lung_coverage_pct: number;
  unvisited_review_areas: string[];
  visited_review_areas?: string[];
  first_visits?: string[];
  time_to_first_mark_s?: number | null;
  total_time_s?: number | null;
  zoom_used?: boolean;
  loupe_used?: boolean;
  heatmap_png_b64?: string | null;
}

export interface TeachingCard {
  label: string;
  display_name: string;
  kind: "focal" | "pattern";
  one_liner: string;
  /**
   * @minItems 1
   */
  key_signs: [string, ...string[]];
  where_it_hides: string[];
  mimics: string[];
  commonly_confused_with: string[];
  search_tip: string;
  radiopaedia_url: string | null;
  review: {
    status: "ai_draft" | "student_reviewed" | "radiologist_reviewed";
    reviewer: string | null;
    date: string | null;
    notes: string | null;
  };
}
