// Build the SYNTHETIC mock-API fixture: copies the 256×256 synthetic test images into public/mock/
// and writes src/api/mock/cases.ts from pipeline/tests/fixtures/synthetic/cases.jsonl.
// These are drawn shapes, not radiographs. Used only when the real API is unavailable (VITE_MOCK=1 / ?mock=1).
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const fx = resolve(here, '../../pipeline/tests/fixtures/synthetic');
const outImg = resolve(here, '../public/mock');
mkdirSync(outImg, { recursive: true });

const cases = readFileSync(resolve(fx, 'cases.jsonl'), 'utf8').trim().split('\n').map((l) => JSON.parse(l));
const slim = cases.map((c) => {
  copyFileSync(resolve(fx, c.image_path), resolve(outImg, `${c.case_id}.png`));
  return {
    case_id: c.case_id, width: c.width, height: c.height, is_normal: c.is_normal, ctr: c.cardiothoracic_ratio ?? null,
    findings: c.findings.map((f) => ({
      finding_id: f.finding_id.split('#')[1], label: f.label, kind: f.kind,
      bbox: f.geometry.bbox, polygon: f.geometry.polygon ?? null, centroid: f.centroid,
      side: f.side ?? null, zones: f.zones ?? [], primary_zone: f.primary_zone ?? null, relative_location: f.relative_location ?? null,
    })),
  };
});
const body = `/* AUTO-GENERATED by scripts/gen-mock.mjs — SYNTHETIC test fixtures (drawn shapes, not radiographs). */
import type { MockCase } from './types';

export const MOCK_CASES: MockCase[] = ${JSON.stringify(slim)};
`;
writeFileSync(resolve(here, '../src/api/mock/cases.ts'), body);
console.log(`mock: ${slim.length} synthetic cases → src/api/mock/cases.ts, images → public/mock/`);
